// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns version of the application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Decision Manager"
                ],
                "summary": "Health Check API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/hello": {
            "get": {
                "description": "Returns a Hello World message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Decision Manager"
                ],
                "summary": "Hello World API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/trigger-decision": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Triggers a decisioning process with the provided parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Decision Manager"
                ],
                "summary": "Triggers decisioning process",
                "parameters": [
                    {
                        "description": "Sequence details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/decision_manager_request_dto.TriggerDecisionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "BadRequest",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "NotFound"
                    },
                    "500": {
                        "description": "InternalServerError"
                    }
                }
            }
        }
    },
    "definitions": {
        "decision_manager_request_dto.TriggerDecisionRequest": {
            "type": "object",
            "required": [
                "applicationId",
                "customerId",
                "leadId",
                "partnerName",
                "stage",
                "workflowId"
            ],
            "properties": {
                "applicationId": {
                    "type": "string",
                    "example": "APP123456"
                },
                "businessType": {
                    "type": "string",
                    "example": "Personal Loan"
                },
                "customerId": {
                    "type": "string",
                    "example": "CUST123456"
                },
                "customerType": {
                    "type": "string",
                    "example": "Personal Loan"
                },
                "leadId": {
                    "type": "string",
                    "example": "00Qtu1587ebf123456"
                },
                "loanCategory": {
                    "type": "string",
                    "example": "Personal Loan"
                },
                "partnerName": {
                    "type": "string",
                    "example": "Samsung"
                },
                "productLine": {
                    "type": "string",
                    "example": "Personal Loan"
                },
                "salesChannelPartnerName": {
                    "type": "string",
                    "example": ""
                },
                "sourcingChannel": {
                    "type": "string",
                    "example": ""
                },
                "nameOfConsolidator": {
                    "type": "string",
                    "example": ""
                },
                "programType": {
                    "type": "string",
                    "example": "Repeat"
                },
                "sourcingProgram": {
                    "type": "string",
                    "example": "Personal Loan"
                },
                "stage": {
                    "type": "string",
                    "example": "Kyc"
                },
                "workflowId": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Api-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/decision-manager",
	Schemes:          []string{},
	Title:            "Swagger UI",
	Description:      "Swagger UI for decision manager Microservice.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
